/*
 * @Copyright: 
 * @file name: File name
 * @Data: Do not edit
 * @LastEditors: jinyt
 * @LastData: 
 * @Describe: 
 */
import {
  Form,
  Field,
  Button,
  List,
  Popup,
  Dialog,
  Notify,
  Icon,
  Uploader,
  ImagePreview,
  Picker,
  Checkbox,
  CheckboxGroup,
  Overlay,
  Loading,
  Progress,
  Tabbar,
  TabbarItem,
  NavBar,
  Tab,
  Tabs,
  Search,
  DropdownMenu,
  DropdownItem,
  SwipeCell,
  RadioGroup,
  Radio,
  Toast,
  Cell,
  Tag,
  Row,
  Col,
  Divider,
  Step,
  Steps,
  Empty,
  CellGroup,
  Grid,
  GridItem,
  PullRefresh,
  Sticky,
  Swipe,
  SwipeItem,
  CountDown,
  Calendar,
  Cascader,
  Switch,
  NoticeBar,
  Circle,
  AddressList,
  AddressEdit,
  ActionBar,
  ActionBarIcon,
  ActionBarButton,
  SubmitBar,
  Stepper,
} from "vant";

export default {
  install(Vue) {
    Vue.use(Form);
    Vue.use(Sticky);
    Vue.use(Field);
    Vue.use(Grid);
    Vue.use(GridItem);
    Vue.use(Button);
    Vue.use(List);
    Vue.use(Popup);
    Vue.use(Dialog);
    Vue.use(Notify);
    Vue.use(Icon);
    Vue.use(Uploader);
    Vue.use(ImagePreview);
    Vue.use(Picker);
    Vue.use(Checkbox);
    Vue.use(CheckboxGroup);
    Vue.use(Overlay);
    Vue.use(Loading);
    Vue.use(Progress);
    Vue.use(Tabbar);
    Vue.use(TabbarItem);
    Vue.use(NavBar);
    Vue.use(Tab);
    Vue.use(Tabs);
    Vue.use(Search);
    Vue.use(DropdownMenu);
    Vue.use(DropdownItem);
    Vue.use(SwipeCell);
    Vue.use(RadioGroup);
    Vue.use(Radio);
    Vue.use(Toast);
    Vue.use(Cell);
    Vue.use(Tag);
    Vue.use(Row);
    Vue.use(Col);
    Vue.use(Divider);
    Vue.use(Step);
    Vue.use(Steps);
    Vue.use(Empty);
    Vue.use(CellGroup)
    Vue.use(PullRefresh)
    Vue.use(Swipe)
    Vue.use(SwipeItem)
    Vue.use(CountDown)
    Vue.use(Calendar)
    Vue.use(Cascader)
    Vue.use(Switch)
    Vue.use(NoticeBar)
    Vue.use(Circle)
    Vue.use(AddressList)
    Vue.use(AddressEdit)
    Vue.use(ActionBar)
    Vue.use(ActionBarIcon)
    Vue.use(ActionBarButton)
    Vue.use(SubmitBar)
    Vue.use(Stepper)
  },
};